# Generated by Django 2.1.7 on 2019-04-02 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('published', models.DateTimeField(default=datetime.datetime.now, verbose_name='Published')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Image')),
                ('summary', models.CharField(max_length=500, verbose_name='Summary')),
                ('body', models.TextField(verbose_name='Body')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'post',
            },
        ),
    ]
